// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 401, DateTimeKind.Utc).AddTicks(8197),
                            PasswordHash = "$2a$11$pWOJdTTUgcfHiGLAMpe9SuHuMWGrDPyekTABwtEJlsHQFrrBePnz6",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(8168),
                            PasswordHash = "$2a$11$p1tEJaGn1OXEzUyPviSsLe302EJJoA1igBbKR0IDoMKfwmpoT6Ayi",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9786),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "rajak@gmail.com",
                            FirstName = "Raja",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chinnapu",
                            Phone = "9376543210",
                            Salary = 580000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9788)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9820),
                            Department = "Marketing",
                            Designation = "Marketing Exec",
                            Email = "roopam@gmail.com",
                            FirstName = "Roopa",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chinnapu",
                            Phone = "9523456780",
                            Salary = 760000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9821)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9827),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "vishnu@gmail.com",
                            FirstName = "Vishnu",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kasireddy",
                            Phone = "9676512340",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9827)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9831),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "venkata@gmail.com",
                            FirstName = "Srinath",
                            JoinDate = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Venkata",
                            Phone = "9576511340",
                            Salary = 950000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9831)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9835),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "rana@gmail.com",
                            FirstName = "keerthi",
                            JoinDate = new DateTime(2019, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Renigunta",
                            Phone = "8576512341",
                            Salary = 750000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9835)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9838),
                            Department = "Engineering",
                            Designation = "Junior Developer",
                            Email = "keerati@gmail.com",
                            FirstName = "Yamini",
                            JoinDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kanuma",
                            Phone = "9076512330",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9838)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9842),
                            Department = "Marketing",
                            Designation = "Agent Operator",
                            Email = "maruthi@gmail.com",
                            FirstName = "Kumar",
                            JoinDate = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Maruthi",
                            Phone = "9116512342",
                            Salary = 850000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9844)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9847),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "tamatam@gmail.com",
                            FirstName = "Manish",
                            JoinDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thamatam",
                            Phone = "9644452340",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9848)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9851),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "hamsa@gmail.com",
                            FirstName = "Prakash",
                            JoinDate = new DateTime(2022, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hamsa",
                            Phone = "9111512340",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9852)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9855),
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "katmurre@gmail.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Katmurre",
                            Phone = "9871512380",
                            Salary = 800000m,
                            Status = "InActive",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9855)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9858),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "mavilla@gmail.com",
                            FirstName = "Vijay",
                            JoinDate = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mavilla",
                            Phone = "9116512340",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9859)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9862),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "thappeta@gmail.com",
                            FirstName = "Naresh",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thappeta",
                            Phone = "9676512340",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9862)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9865),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "penderi@gmail.com",
                            FirstName = "Santhosh",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Penderi",
                            Phone = "9676512340",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9865)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9868),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "jitta@gmail.com",
                            FirstName = "Padhhu",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jitta",
                            Phone = "9676512340",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 14, 27, 31, 626, DateTimeKind.Utc).AddTicks(9869)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
